# Generated by Django 5.2.8 on 2026-01-22 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_teacher_qualification_student_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='ci_1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='mark',
            name='ci_2',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='mark',
            name='ci_3',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.FloatField(default=0),
        ),
    ]
